
import { StoreProduct } from './types';

export const getFutureDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const SHIPPING_RATES: Record<string, number> = {
  'USA': 12,
  'UK': 10,
  'Canada': 11,
  'Australia': 13,
  'UAE': 8,
  'Germany': 9,
  'Singapore': 7,
  'India': 5,
};

export const COUNTRIES = Object.keys(SHIPPING_RATES);

export const STORE_PRODUCTS: StoreProduct[] = [
  {
    id: 'p1',
    name: 'Brass Diya Set',
    price: 25,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/diya/400/400',
    weight: 0.5,
    description: 'This exquisite handcrafted Brass Diya (Oil Lamp) set is a perfect addition to your spiritual space. Made from high-quality solid brass, it features intricate traditional engravings that reflect elegance and devotion.',
    dimensions: { length: 12, width: 8, height: 6, unit: 'cm' },
    material: 'Solid Brass',
    origin: 'Moradabad, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p2',
    name: 'Sandalwood Incense Sticks',
    price: 10,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/incense/400/400',
    weight: 0.2,
    description: 'Immerse yourself in the calming aroma of pure Sandalwood. These premium incense sticks are hand-rolled using natural resins and essential oils. Perfect for meditation, yoga, or creating a peaceful home environment.',
    dimensions: { length: 20, width: 2, height: 2, unit: 'cm' },
    material: 'Natural Resins & Sandalwood Oil',
    origin: 'Mysore, India',
    estimatedDelivery: getFutureDate(1),
  },
  {
    id: 'p3',
    name: 'Decorative Silk Pouch',
    price: 5,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/pouch/400/400',
    weight: 0.1,
    estimatedDelivery: getFutureDate(3),
  },
  {
    id: 'p4',
    name: 'Handcrafted Elephant Statue',
    price: 45,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/elephant/400/400',
    weight: 1.2,
    description: 'A majestic statement piece for your home decor. This elephant statue is meticulously hand-carved by skilled artisans using premium sustainable wood. The intricate details capture the grandeur of the Indian elephant.',
    dimensions: { length: 25, width: 12, height: 20, unit: 'cm' },
    material: 'Sheesham Wood',
    origin: 'Saharanpur, India',
    estimatedDelivery: getFutureDate(5),
  },
  {
    id: 'p5',
    name: 'Copper Kalash',
    price: 30,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/kalash/400/400',
    weight: 0.8,
    description: 'A traditional Copper Kalash, essential for Vedic rituals and pooja ceremonies. Crafted from high-purity hammered copper, it retains water purity and adds a spiritual touch to your altar.',
    dimensions: { length: 15, width: 15, height: 18, unit: 'cm' },
    material: '100% Pure Copper',
    origin: 'Pune, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p6',
    name: 'Wall Hanging Lantern',
    price: 20,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/lantern/400/400',
    weight: 0.6,
    estimatedDelivery: getFutureDate(4),
  },
  {
    id: 'p7',
    name: 'Silver Plated Pooja Thali',
    price: 55,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/thali/400/400',
    weight: 1.5,
    description: 'A luxurious silver-plated Thali set for special occasions and weddings. The set includes a beautiful large plate, intricate bowls, and a traditional diya. Finished with a tarnish-resistant coating for long-lasting shine.',
    dimensions: { length: 32, width: 32, height: 4, unit: 'cm' },
    material: 'Silver Plated Steel',
    origin: 'Delhi, India',
    estimatedDelivery: getFutureDate(3),
  },
  {
    id: 'p8',
    name: 'Ganesh Idol (Eco-friendly)',
    price: 15,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/ganesh/400/400',
    weight: 0.4,
    description: 'Bring home the remover of obstacles. This eco-friendly Ganesh idol is handcrafted from natural clay and painted with non-toxic, organic pigments. It dissolves harmlessly in water, making it perfect for rituals.',
    dimensions: { length: 10, width: 8, height: 15, unit: 'cm' },
    material: 'Natural Clay',
    origin: 'Maharashtra, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p9',
    name: 'Hand-painted Diya Set (12pcs)',
    price: 7.5,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/diyas/400/400',
    weight: 0.3,
    estimatedDelivery: getFutureDate(1),
  },
  {
    id: 'p10',
    name: 'Traditional Toran (Door Hanging)',
    price: 10.5,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/toran/400/400',
    weight: 0.2,
    description: 'A vibrant floral door hanging that signifies a warm welcome. Handcrafted with traditional beadwork and embroidery, it adds a festive touch to any entrance while celebrating Indian heritage.',
    dimensions: { length: 90, width: 10, height: 2, unit: 'cm' },
    material: 'Fabric & Beads',
    origin: 'Gujarat, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p11',
    name: 'Rangoli Stencil Kit',
    price: 5.5,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/rangoli/400/400',
    weight: 0.1,
    estimatedDelivery: getFutureDate(1),
  },
  {
    id: 'p12',
    name: 'Mehendi Cone Set (Pack of 6)',
    price: 3.75,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/mehendi/400/400',
    weight: 0.2,
    estimatedDelivery: getFutureDate(1),
  },
  {
    id: 'p13',
    name: 'Kaju Katli Sweet Box (500g)',
    price: 18.50,
    category: 'Sweets & Snacks',
    image: 'https://picsum.photos/seed/kajukatli/400/400',
    weight: 0.5,
    description: 'Authentic melt-in-your-mouth Kaju Katli made from premium cashews, pure desi ghee, and silver leaf foil. Sealed fresh for international export.',
    dimensions: { length: 20, width: 15, height: 4, unit: 'cm' },
    material: 'Pure Cashews & Ghee',
    origin: 'Delhi, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p14',
    name: 'Haldiram Special Bhujia (1kg)',
    price: 9.50,
    category: 'Sweets & Snacks',
    image: 'https://picsum.photos/seed/bhujia/400/400',
    weight: 1.0,
    description: 'Crispy and savory Bikaneri moth bean bhujia. A quintessential Indian snack seasoned with authentic spices.',
    dimensions: { length: 25, width: 18, height: 8, unit: 'cm' },
    material: 'Moth Bean Flour & Spices',
    origin: 'Bikaner, India',
    estimatedDelivery: getFutureDate(1),
  },
  {
    id: 'p15',
    name: 'Pure Kashmir Saffron (1g Jar)',
    price: 24.00,
    category: 'Spices & Gourmet',
    image: 'https://picsum.photos/seed/saffron/400/400',
    weight: 0.05,
    description: 'Grade-1 A++ Mongra Kashmiri Saffron (Zafran). Hand-harvested deep crimson threads with rich aroma and golden color.',
    dimensions: { length: 5, width: 5, height: 5, unit: 'cm' },
    material: '100% Pure Saffron',
    origin: 'Pampore, Kashmir, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p16',
    name: 'Organic Assam Black Tea (500g)',
    price: 12.50,
    category: 'Spices & Gourmet',
    image: 'https://picsum.photos/seed/assamtea/400/400',
    weight: 0.5,
    description: 'Strong, malty, and rich CTC black tea leaves directly from Assam tea gardens. Perfect for authentic Indian Masala Chai.',
    dimensions: { length: 15, width: 10, height: 20, unit: 'cm' },
    material: 'Black Tea Leaves',
    origin: 'Assam, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p17',
    name: 'Brass Pooja Bell (Ghanti)',
    price: 14.00,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/poojabell/400/400',
    weight: 0.4,
    description: 'Hand-cast solid brass ritual hand bell featuring Garuda at the handle. Clear, resonant acoustic tone for daily pooja.',
    dimensions: { length: 8, width: 8, height: 16, unit: 'cm' },
    material: 'Solid Brass',
    origin: 'Aligarh, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p18',
    name: 'Wooden Masala Dabba Spice Box',
    price: 26.00,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/spicebox/400/400',
    weight: 0.9,
    description: 'Handcrafted Sheesham wood traditional Indian spice container with 7 circular compartments and transparent glass lid.',
    dimensions: { length: 22, width: 22, height: 8, unit: 'cm' },
    material: 'Sheesham Wood',
    origin: 'Saharanpur, India',
    estimatedDelivery: getFutureDate(3),
  },
  {
    id: 'p19',
    name: 'Mysore Silk Zari Dupatta',
    price: 32.00,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/silkdupatta/400/400',
    weight: 0.25,
    description: 'Luxurious soft Mysore art silk stole with rich gold zari border. Elegant gift choice for festive celebrations.',
    dimensions: { length: 220, width: 90, height: 1, unit: 'cm' },
    material: 'Art Silk & Gold Zari',
    origin: 'Mysore, India',
    estimatedDelivery: getFutureDate(3),
  },
  {
    id: 'p20',
    name: 'Brass Urli Bowl for Floating Flowers',
    price: 34.00,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/urli/400/400',
    weight: 1.2,
    description: 'Traditional South Indian brass Urli bowl designed for floating flower petals and tea lights. Adds divine warmth to entryways.',
    dimensions: { length: 25, width: 25, height: 10, unit: 'cm' },
    material: 'Solid Brass',
    origin: 'Kumbakonam, India',
    estimatedDelivery: getFutureDate(3),
  },
  {
    id: 'p21',
    name: 'Ayurvedic Neem & Turmeric Soap Set',
    price: 8.50,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/herbalsoap/400/400',
    weight: 0.35,
    description: 'Handmade cold-processed herbal soaps enriched with organic neem, wild turmeric, and cold-pressed coconut oil.',
    dimensions: { length: 12, width: 8, height: 6, unit: 'cm' },
    material: 'Organic Herbal Extracts',
    origin: 'Kerala, India',
    estimatedDelivery: getFutureDate(1),
  },
  {
    id: 'p22',
    name: 'Gulab Jamun Tin Box (1kg)',
    price: 15.00,
    category: 'Sweets & Snacks',
    image: 'https://picsum.photos/seed/gulabjamun/400/400',
    weight: 1.2,
    description: 'Soft milk-solid dumplings soaked in cardamom infused rose sugar syrup. Sealed for long shelf life.',
    dimensions: { length: 15, width: 15, height: 14, unit: 'cm' },
    material: 'Khoa & Sugar Syrup',
    origin: 'Kolkata, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p23',
    name: 'South Indian Filter Coffee Powder (500g)',
    price: 11.00,
    category: 'Spices & Gourmet',
    image: 'https://picsum.photos/seed/filtercoffee/400/400',
    weight: 0.5,
    description: '80:20 Roasted Arabica Coffee & Chicory blend from Chikmagalur estates. Rich crema and authentic aroma.',
    dimensions: { length: 14, width: 8, height: 18, unit: 'cm' },
    material: 'Roasted Coffee & Chicory',
    origin: 'Chikmagalur, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p24',
    name: 'Hand-carved Sandalwood Elephant Keychain (5pcs)',
    price: 12.00,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/keychain/400/400',
    weight: 0.15,
    description: 'Charming miniature fragrant sandalwood elephant keychains. Ideal return gift for weddings and pooja functions.',
    dimensions: { length: 10, width: 5, height: 3, unit: 'cm' },
    material: 'Sandalwood & Metal',
    origin: 'Jaipur, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p25',
    name: 'Dry Fruit Laddu Box (500g)',
    price: 22.00,
    category: 'Sweets & Snacks',
    image: 'https://picsum.photos/seed/dryfruitladdoo/400/400',
    weight: 0.5,
    description: 'Sugar-free energy balls made with dates, figs, almonds, cashews, pistachios, and pure ghee.',
    dimensions: { length: 20, width: 15, height: 5, unit: 'cm' },
    material: 'Nuts, Dates & Ghee',
    origin: 'Jodhpur, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p26',
    name: 'Pure A2 Desi Cow Ghee (500ml Glass Jar)',
    price: 16.50,
    category: 'Spices & Gourmet',
    image: 'https://picsum.photos/seed/a2ghee/400/400',
    weight: 0.6,
    description: 'Traditional Bilona churned A2 Gir cow ghee. Rich aromatic granular texture and high nutritional value.',
    dimensions: { length: 10, width: 10, height: 16, unit: 'cm' },
    material: 'Pure A2 Milk Fat',
    origin: 'Gujarat, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p27',
    name: 'Brass Laxmi & Ganesh Idol Set',
    price: 38.00,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/laxmiganesh/400/400',
    weight: 0.9,
    description: 'Handcrafted solid brass Goddess Lakshmi and Lord Ganesha idols for auspicious home mandir setup.',
    dimensions: { length: 15, width: 8, height: 12, unit: 'cm' },
    material: 'Solid Brass',
    origin: 'Moradabad, India',
    estimatedDelivery: getFutureDate(3),
  },
  {
    id: 'p28',
    name: 'Jaipuri Bandhani Cotton Dupatta',
    price: 14.00,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/bandhani/400/400',
    weight: 0.2,
    description: 'Vibrant hand tie-dyed pure cotton Bandhej dupatta with mirror work border. Traditional Rajasthani craft.',
    dimensions: { length: 220, width: 95, height: 1, unit: 'cm' },
    material: '100% Pure Cotton',
    origin: 'Jaipur, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p29',
    name: 'Hammered Copper Water Bottle (1000ml)',
    price: 19.50,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/copperbottle/400/400',
    weight: 0.35,
    description: 'Pure copper leak-proof water bottle with ergonomic hand-hammered texture for health benefits.',
    dimensions: { length: 8, width: 8, height: 27, unit: 'cm' },
    material: '100% Pure Copper',
    origin: 'Mathura, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p30',
    name: 'Whole Green Cardamom (Elaichi 250g)',
    price: 18.00,
    category: 'Spices & Gourmet',
    image: 'https://picsum.photos/seed/cardamom/400/400',
    weight: 0.25,
    description: 'Bold 8mm extra-green cardamom pods sourced directly from Idukki spice hills. Intense aroma and taste.',
    dimensions: { length: 12, width: 8, height: 18, unit: 'cm' },
    material: 'Whole Cardamom Pods',
    origin: 'Kerala, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p31',
    name: 'Soan Papdi Flaky Sweet Pack (500g)',
    price: 11.50,
    category: 'Sweets & Snacks',
    image: 'https://picsum.photos/seed/soanpapdi/400/400',
    weight: 0.5,
    description: 'Crisp, multi-layered flaky cardamom sweet garnished with sliced almonds and pistachios.',
    dimensions: { length: 20, width: 14, height: 6, unit: 'cm' },
    material: 'Gram Flour, Sugar & Ghee',
    origin: 'Nagpur, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p32',
    name: 'Traditional Brass Filter Coffee Dabara Set (2 Sets)',
    price: 21.00,
    category: 'Decorative',
    image: 'https://picsum.photos/seed/brassdabara/400/400',
    weight: 0.5,
    description: 'Authentic heavy brass Dabara and tumbler set for serving traditional South Indian filter coffee.',
    dimensions: { length: 12, width: 12, height: 8, unit: 'cm' },
    material: 'Solid Brass',
    origin: 'Tanjore, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p33',
    name: 'Terracotta Handpainted Matki Diya Set (6pcs)',
    price: 9.00,
    category: 'Pooja',
    image: 'https://picsum.photos/seed/matkidiya/400/400',
    weight: 0.4,
    description: 'Artisanal clay oil lamps with vibrant acrylic painting and gold glitter borders.',
    dimensions: { length: 15, width: 10, height: 6, unit: 'cm' },
    material: 'Natural Terracotta',
    origin: 'Varanasi, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p34',
    name: 'Handmade Madhubani Art Coasters Set (6pcs)',
    price: 13.50,
    category: 'Return Gifts',
    image: 'https://picsum.photos/seed/madhubani/400/400',
    weight: 0.3,
    description: 'Wooden tea coasters featuring traditional Mithila folk art painting with heat-resistant gloss finish.',
    dimensions: { length: 10, width: 10, height: 4, unit: 'cm' },
    material: 'MDF Wood & Acrylics',
    origin: 'Bihar, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p35',
    name: 'Special Herbal Chyawanprash (1kg)',
    price: 17.50,
    category: 'Spices & Gourmet',
    image: 'https://picsum.photos/seed/chyawanprash/400/400',
    weight: 1.1,
    description: 'Classic Ayurvedic health tonic crafted with organic Amla, honey, saffron, and 40+ medicinal herbs.',
    dimensions: { length: 12, width: 12, height: 18, unit: 'cm' },
    material: 'Wild Amla & Medicinal Herbs',
    origin: 'Haridwar, India',
    estimatedDelivery: getFutureDate(2),
  },
  {
    id: 'p36',
    name: 'Kashmiri Zafran Almond Cookies (400g Box)',
    price: 13.00,
    category: 'Sweets & Snacks',
    image: 'https://picsum.photos/seed/zafrancookies/400/400',
    weight: 0.4,
    description: 'Handmade butter bakery cookies infused with pure saffron strands and crunchy crushed roasted almonds.',
    dimensions: { length: 18, width: 12, height: 7, unit: 'cm' },
    material: 'Saffron, Almonds & Butter',
    origin: 'Kashmir, India',
    estimatedDelivery: getFutureDate(2),
  }
];

export const PROHIBITED_ITEMS = [
  'Aerosols, perfumes, and pressurized containers',
  'Alcoholic beverages and tobacco products',
  'Ammunition, firearms, and explosives',
  'Batteries (standalone lithium-ion or lead-acid)',
  'Cash, currency, and negotiable instruments',
  'Corrosive substances (acids, batteries, etc.)',
  'Drugs, narcotics, and illegal substances',
  'Flammable liquids (paints, fuels, nail polish)',
  'Fresh fruits, vegetables, and meat products',
  'Hazardous waste and toxic chemicals',
  'Human remains or ashes',
  'Infectious substances and biological materials',
  'Knives, swords, and other sharp weapons',
  'Live animals and protected wildlife products',
  'Magnetized materials',
  'Oxidizing agents and organic peroxides',
  'Pornographic or offensive materials',
  'Radioactive materials',
  'Seeds, plants, and soil (without USDA permit)',
];

export const SHIPPING_DATES = [
  getFutureDate(5),
  getFutureDate(10),
  getFutureDate(15),
  getFutureDate(20),
  getFutureDate(25),
];

export const PICKUP_SLOTS = Array.from({ length: 15 }).map((_, i) => ({
  date: getFutureDate(i),
  times: ['9–11 AM', '11–1 PM', '1–3 PM', '3–5 PM', '5–7 PM', '7–9 PM']
}));

export const WAREHOUSE_ADDRESS = {
  name: 'Jiffex Main Warehouse',
  fullName: 'Jiffex Main Warehouse',
  street: 'Plot No. 45, Sector 18',
  addressLine1: 'Plot No. 45, Sector 18',
  city: 'Gurgaon',
  state: 'Haryana',
  zip: '122015',
  zipCode: '122015',
  country: 'India',
  phone: '+91 124 4567890'
};

export const INDIAN_STORES = [
  { name: 'Amazon India', url: 'https://www.amazon.in', logo: 'https://www.vectorlogo.zone/logos/amazon/amazon-icon.svg' },
  { name: 'Flipkart', url: 'https://www.flipkart.com', logo: 'https://www.vectorlogo.zone/logos/flipkart/flipkart-icon.svg' },
  { name: 'Myntra', url: 'https://www.myntra.com', logo: 'https://www.vectorlogo.zone/logos/myntra/myntra-icon.svg' },
  { name: 'Ajio', url: 'https://www.ajio.com', logo: 'https://www.vectorlogo.zone/logos/ajio/ajio-icon.svg' },
  { name: 'Nykaa', url: 'https://www.nykaa.com', logo: 'https://www.vectorlogo.zone/logos/nykaa/nykaa-icon.svg' },
  { name: 'FirstCry', url: 'https://www.firstcry.com', logo: 'https://www.vectorlogo.zone/logos/firstcry/firstcry-icon.svg' },
];

export const COMPANY_DETAILS = {
  name: "Jiffex Fulfilment Private Limited",
  fullName: "Jiffex Fulfilment Private Limited",
  gstin: "36AAHCJ4656R1ZQ",
  address: "Plot No 20, Siddartha Nagar North, Hyderabad 500038",
  email: "support@jiffex.shop",
  phone: "+91 99999 00000",
  website: "www.jiffex.shop"
};
